package io.keydra.connections.mapper;

import io.keydra.connections.dto.ConnectionRequest;
import io.keydra.connections.dto.ConnectionResponse;
import io.keydra.connections.dto.ConnectionStatus;
import io.keydra.connections.entity.ConnectionProfile;
import io.keydra.connections.entity.ServerFlavor;
import io.keydra.engine.EngineType;
import org.mapstruct.AfterMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.Named;

/**
 * Translates between the persistence model and the wire contracts.
 *
 * <p>Generated by MapStruct: field-by-field copying is exactly the code that rots when a field is
 * added and someone forgets a line. {@code unmappedTargetPolicy=ERROR} is set in the build, so an
 * unmapped field fails compilation instead of silently arriving as null.
 *
 * <p>The one rule that is not a plain copy is stated explicitly below. The tunnel's used to be here
 * too; it is a row of its own now, and a profile points at it by id.
 */
@Mapper(componentModel = "jakarta")
public interface ConnectionMapper {

    /**
     * Entity plus live status to the wire shape.
     *
     * <p>{@code hasPassword} is derived rather than copied: the response has no password field at
     * all, so a stored secret cannot be serialised by accident.
     */
    @Mapping(target = "hasPassword", source = "profile.password", qualifiedByName = "isPresent")
    // The same rule for the client key: whether one is stored, never what it is.
    @Mapping(
            target = "hasClientKey",
            source = "profile.tlsClientKey",
            qualifiedByName = "isPresent")
    // And for what opens it.
    @Mapping(
            target = "hasClientKeyPassphrase",
            source = "profile.tlsClientKeyPassphrase",
            qualifiedByName = "isPresent")
    // The console allowance is a list to whoever reads it and a column to whoever stores it.
    @Mapping(
            target = "consoleAllowed",
            source = "profile.consoleAllowed",
            qualifiedByName = "asList")
    ConnectionResponse toResponse(ConnectionProfile profile, ConnectionStatus status);

    /**
     * Applies a request onto an existing profile.
     *
     * <p>The id belongs to persistence and the password has its own rule, so both are excluded here
     * and the password is handled in {@link #applyPassword}.
     */
    @Mapping(target = "id", ignore = true)
    // Which database a request is working in is not part of the saved profile.
    @Mapping(target = "selectedDatabase", ignore = true)
    @Mapping(target = "password", ignore = true)
    // The certificates follow the secrets' own rule and are set below.
    @Mapping(target = "tlsCaCert", ignore = true)
    @Mapping(target = "tlsClientCert", ignore = true)
    @Mapping(target = "tlsClientKey", ignore = true)
    @Mapping(target = "tlsClientKeyPassphrase", ignore = true)
    // A list on the wire, a column in the row: not a copy, so it is written out below.
    @Mapping(target = "consoleAllowed", ignore = true)
    void apply(ConnectionRequest request, @MappingTarget ConnectionProfile profile);

    /**
     * Password: absent means keep, empty means clear.
     *
     * <p>The API never returns the stored secret, so an edit form arrives with the field empty.
     * Treating that as "clear it" would silently drop credentials on every save.
     */
    @AfterMapping
    default void applyPassword(
            ConnectionRequest request, @MappingTarget ConnectionProfile profile) {
        if (request.password() != null) {
            profile.password = request.password().isEmpty() ? null : request.password();
        }
    }

    /**
     * The certificates: absent means keep, empty means clear.
     *
     * <p>The same rule as the password, and for a related reason. The two certificates are
     * returned, so a form could send them back — but an edit that is about the port should not have
     * to, and a client key never comes back at all. One rule for the three keeps a partial edit
     * from meaning three different things.
     */
    @AfterMapping
    default void applyCertificates(
            ConnectionRequest request, @MappingTarget ConnectionProfile profile) {
        if (request.tlsCaCert() != null) {
            profile.tlsCaCert = request.tlsCaCert().isBlank() ? null : request.tlsCaCert().strip();
        }
        if (request.tlsClientCert() != null) {
            profile.tlsClientCert =
                    request.tlsClientCert().isBlank() ? null : request.tlsClientCert().strip();
        }
        if (request.tlsClientKey() != null) {
            profile.tlsClientKey =
                    request.tlsClientKey().isBlank() ? null : request.tlsClientKey().strip();
        }
        // The passphrase is not stripped. Leading or trailing space in a PEM block is noise a
        // parser ignores; in a passphrase it is a character, and silently removing it would turn
        // a key that opens into one that does not.
        if (request.tlsClientKeyPassphrase() != null) {
            profile.tlsClientKeyPassphrase =
                    request.tlsClientKeyPassphrase().isEmpty()
                            ? null
                            : request.tlsClientKeyPassphrase();
        }
    }

    /** Engine is optional on the wire; a profile without one speaks RESP. */
    @AfterMapping
    default void applyEngineDefault(
            ConnectionRequest request, @MappingTarget ConnectionProfile profile) {
        if (request.engine() == null) {
            profile.engine = EngineType.RESP;
        }
    }

    /** Server is optional on the wire; a profile that does not say waits for the target to. */
    @AfterMapping
    default void applyFlavorDefault(
            ConnectionRequest request, @MappingTarget ConnectionProfile profile) {
        if (request.flavor() == null) {
            profile.flavor = ServerFlavor.UNKNOWN;
        }
    }

    /**
     * The console allowance: absent means keep, empty means clear.
     *
     * <p>The same rule as the password and the certificates, although this one is returned. An edit
     * that is about the port should not have to send it back, and a form that omitted it would
     * otherwise be widening or narrowing what the console may do by accident.
     *
     * <p>Normalised on the way in — trimmed, lowercased, blanks dropped — so that what is compared
     * against the deny-list is compared the same way whoever typed it wrote it.
     */
    @AfterMapping
    default void applyConsoleAllowed(
            ConnectionRequest request, @MappingTarget ConnectionProfile profile) {
        if (request.consoleAllowed() == null) {
            return;
        }
        String joined =
                request.consoleAllowed().stream()
                        .filter(java.util.Objects::nonNull)
                        .map(name -> name.trim().toLowerCase(java.util.Locale.ROOT))
                        .filter(name -> !name.isEmpty())
                        .distinct()
                        .collect(java.util.stream.Collectors.joining(","));
        profile.consoleAllowed = joined.isEmpty() ? null : joined;
    }

    @Named("asList")
    static java.util.List<String> asList(String stored) {
        if (stored == null || stored.isBlank()) {
            return java.util.List.of();
        }
        return java.util.Arrays.stream(stored.split(","))
                .map(String::trim)
                .filter(name -> !name.isEmpty())
                .toList();
    }

    @Named("isPresent")
    static boolean isPresent(String value) {
        return value != null && !value.isBlank();
    }
}
