-- Keydra's own schema: connection profiles, console history and the audit log.
--
-- Written to match what the entities declare, read out of a database Hibernate built from
-- them rather than from reading the classes and hoping. FlywaySchemaTest migrates a
-- database with this file and then asks Hibernate to validate it, so the two cannot drift
-- apart without a test failing.
--
-- The targets Keydra manages have nothing here. Their data lives in them.

CREATE TABLE connection_profile (
    id                 BIGINT         NOT NULL,
    name               VARCHAR(255)   NOT NULL,
    host               VARCHAR(255)   NOT NULL,
    port               INTEGER        NOT NULL,
    username           VARCHAR(255),
    -- Encrypted before it gets here; the column holds ciphertext, never a password.
    password           VARCHAR(2048),
    tls                BOOLEAN        NOT NULL,
    db_index           INTEGER        NOT NULL,
    engine             VARCHAR(16)    NOT NULL,
    type               VARCHAR(16)    NOT NULL,
    sentinelmastername VARCHAR(255),
    notes              VARCHAR(2000),
    tunnel_enabled     BOOLEAN        NOT NULL,
    tunnel_host        VARCHAR(255),
    -- Not null because the entity's field is a primitive int, which cannot hold NULL:
    -- Hibernate validates happily against a nullable column and then throws on the first
    -- row that has one.
    tunnel_port        INTEGER        NOT NULL,
    tunnel_username    VARCHAR(255),
    -- Encrypted, like the target password above.
    tunnel_password    VARCHAR(2048),
    tunnel_private_key VARCHAR(8192),
    tunnel_passphrase  VARCHAR(2048),
    CONSTRAINT connection_profile_pkey PRIMARY KEY (id),
    CONSTRAINT connection_profile_port_check CHECK (port BETWEEN 1 AND 65535),
    CONSTRAINT connection_profile_db_index_check CHECK (db_index >= 0),
    CONSTRAINT connection_profile_engine_check CHECK (engine IN ('RESP')),
    CONSTRAINT connection_profile_type_check
        CHECK (type IN ('STANDALONE', 'CLUSTER', 'SENTINEL'))
);

-- Increment 50 because that is Hibernate's default allocation size for a sequence
-- generator, and a mismatch there hands out ids the application believes it owns.
CREATE SEQUENCE connection_profile_seq START WITH 1 INCREMENT BY 50;

CREATE INDEX idx_connection_profile_name ON connection_profile (name);

CREATE TABLE command_history (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    connection_id BIGINT        NOT NULL,
    line          VARCHAR(4096) NOT NULL,
    executed_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT command_history_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_command_history_connection ON command_history (connection_id, id);

CREATE TABLE audit_event (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    actor         VARCHAR(255) NOT NULL,
    action        VARCHAR(64)  NOT NULL,
    connection_id BIGINT,
    -- What was acted on, never what it was set to: a value written to a target may be a
    -- secret, and this table is queryable by every admin.
    detail        VARCHAR(1024),
    succeeded     BOOLEAN      NOT NULL,
    CONSTRAINT audit_event_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_audit_at ON audit_event (at);
CREATE INDEX idx_audit_actor ON audit_event (actor);
CREATE INDEX idx_audit_connection ON audit_event (connection_id);
